version: '3.8'
services:
  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=os_controller
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer:4
    container_name: adminer_container
    restart: always
    ports:
      - 8080:8080
      
volumes:
  db:
    driver: local